Story/1821
unipartdigital/udes-open pull request #647
Opened 2022-06-06 12:53 UTC by armandcela

2022-06-07 12:45 UTC, kdwyer approved these changes

2022-06-07 13:42 UTC, PeterAlabaster commented on addons/udes_sale_stock/exceptions.py
> +class CombinedException(ValidationError):
This looks as if it could live in `udes_common`

2022-06-07 13:45 UTC, PeterAlabaster requested changes
Looks good just 2 minor comments

2022-06-08 07:28 UTC, PeterAlabaster approved these changes

2022-06-09 10:02 UTC, merged